# CNB 部署配置
main:
  push:
    - docker:
        image: node:22
      stages:
        - name: install dependencies
          script: npm install
        - name: start server
          script: node server.js
          port: 8080

$:
  vscode:
    - env:
        CNB_WELCOME_CMD: "npm start"
      stages:
        - name: install dependencies
          script: npm install
