# CNB 部署配置
main:
  push:
    - docker:
        image: node:22
      stages:
        - name: install dependencies
          script: npm install
        - name: start server
          script: node server.js
          port: 8080

$:
  vscode:
    - docker:
        image: node:22
      stages:
        - name: install dependencies
          script: npm install
        - name: start server
          script: npm start
          port: 8080
